//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jungler_Timers.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jungler_Timers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream baronNashor0 {
            get {
                return ResourceManager.GetStream("baronNashor0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream baronNashor30 {
            get {
                return ResourceManager.GetStream("baronNashor30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream blueBuffAlly0 {
            get {
                return ResourceManager.GetStream("blueBuffAlly0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream blueBuffAlly30 {
            get {
                return ResourceManager.GetStream("blueBuffAlly30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream blueBuffEnemy0 {
            get {
                return ResourceManager.GetStream("blueBuffEnemy0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream blueBuffEnemy30 {
            get {
                return ResourceManager.GetStream("blueBuffEnemy30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream drake0 {
            get {
                return ResourceManager.GetStream("drake0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream drake30 {
            get {
                return ResourceManager.GetStream("drake30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream redBuffAlly0 {
            get {
                return ResourceManager.GetStream("redBuffAlly0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream redBuffAlly30 {
            get {
                return ResourceManager.GetStream("redBuffAlly30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream redBuffEnemy0 {
            get {
                return ResourceManager.GetStream("redBuffEnemy0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream redBuffEnemy30 {
            get {
                return ResourceManager.GetStream("redBuffEnemy30", resourceCulture);
            }
        }
    }
}
